on: pull_request
name: PHPLint
jobs:
  phplint:
    name: Exec PHP Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Checking PHP syntax error
        uses: overtrue/phplint@master
        with:
          path: .
          options: --exclude=*.log
      - name: Checking PHP coding rules
        uses: rtCamp/action-phpcs-code-review@v2.0.3
        env:
          GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
          SKIP_FOLDERS: "tests,.github"
        with:
          args: "PSR12"
