name: PHPLint
on:
  push:
  pull_request:
    types: edited

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Checking PHP syntax error
        uses: overtrue/phplint@master
        with:
          path: ./laravel
          options: --exclude=*.log
