name: PHPLint
on:
  push:
  pull_request:
    types: edited

jobs:
  phplint:
    name: Exec PHP Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version
      - name: Checking PHP syntax error
        uses: overtrue/phplint@master
        with:
          path: .
          options: --exclude=*.log
      - name: Checking PHP code rules
        uses: tinovyatkin/action-php-codesniffer@v1
        with:
          files: "**.php"
          phpcs_path: php phpcs.phar
          standard: phpcs.xml
