name: PHPLint
on:
  push:
  pull_request:
    types: edited

jobs:
  phplint:
    name: PHPLint
    runs-on: ubuntu-latest
    steps:
      - name: Exec PHPLint
        uses: overtrue/phplint@master
        with:
          path: .
          options: --exclude=*.log
